version: '2'

services:

  amm:
    image: epflidevelop/amm
    environment:
      SECRET_KEY: ${SECRET_KEY}
      LDAP_USER_BASE_DN: ${LDAP_USER_BASE_DN}
      LDAP_USER_SEARCH_ATTR: ${LDAP_USER_SEARCH_ATTR}
      LDAP_SERVER: ${LDAP_SERVER}
      CACHE_REDIS_LOCATION: ${CACHE_REDIS_LOCATION}
      CACHE_REDIS_CLIENT_CLASS: ${CACHE_REDIS_CLIENT_CLASS}
      DJANGO_SETTINGS_MODULE: config.settings.base
      DJANGO_HOST: ${SERVICE_FQDN}
    expose:
      - 8000
    external_links:
      - ${REDIS_SERVICE}

  lb:
    image: rancher/lb-service-haproxy:v0.4.9
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
    ports:
      - 443
