---
version: '2'
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
    - ${MYSQL_EXPORT_PORT}:3306
    #mem_limit: ${MEM_LIMIT}
    command: --max-connections=${MAX_CONNECTIONS}
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: {}
