# (c) All rights reserved. ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, VPSI, 2017
---
name: dns
description: |
  Rancher external-dns RFC2136 driver with included Bind9 server.
version: v1.0.0
category: DNS

