# (c) All rights reserved. ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, VPSI, 2017
---
name: MariaDB-resources-contraints
description: |
  MariaDB The world's most popular open source database
version: v1
category: Databases

