# (c) All rights reserved. ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, VPSI, 2017
---
name: MySQL-resources-contraints
description: |
  MySQL The world's most popular open source database
version: v76
category: Databases
