---
version: '2'
catalog:
  name: "Bind9 DNS with Automatic Updates"
  version: "v1.0.0"
  description: "Domain Name Server powered by Bind9"
  minimum_rancher_version: v1.2.0-pre4-rc1
  questions:
    - variable: "ROOT_DOMAIN"
      label: "The root domain to manage in bind9"
      description: "This root domain will be managed by the Bind9 server. Updates and axfr requests will be made on this domain"
      type: "string"
      required: true
    - variable: "TSIG_KEYNAME"
      label: "Bind9 TSIG Keyname"
      description: "The TSIG keyname"
      type: "string"
      required: true
    - variable: "TSIG_SECRET"
      label: "Bind9 TSIG Key (base64 encoded)"
      description: "The TSIG key. Must be base64 encoded"
      type: "string"
      required: true
    - variable: "BIND9_PORT"
      label: "Bind9 port"
      description: "Bind9 port to expose on host. Will be used to bind both TCP and UDP"
      type: "string"
      default: 53
      required: true
    - variable: "BIND9_FORWARDERS"
      label: "Bind9 dns forwarders"
      description: "The DNS forwarders"
      type: "string"
      default: 8.8.8.8;8.8.4.4;
      required: true
    - variable: "TTL"
      label: "TTL"
      description: "The resource record cache time to live (TTL), in seconds"
      type: "int"
      default: 60
      required: false
    - variable: "NAME_TEMPLATE"
      label: "DNS Name Template"
      description: |
        Name template used to construct the subdomain part (left of the zone/domain name) of the DNS record names.
        Supported placeholders: %{{service_name}}, %{{stack_name}}, %{{environment_name}}.
        By default DNS entries will be named '<service>.<stack>.<environment>.<domain>'.
      type: "string"
      default: "%{{service_name}}.%{{stack_name}}.%{{environment_name}}"
      required: false

services:
  dns-server:
    scale: 1
    health_check:
      port: ${BIND9_PORT}
      interval: 2000
      initializing_timeout: 20000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000
  rfc2136dns:
    health_check:
      port: 1000
      interval: 5000
      unhealthy_threshold: 3
      request_line: GET / HTTP/1.0
      healthy_threshold: 2
      response_timeout: 2000
